services:
  mongodb:
    image: mongo:7
    container_name: mongo_server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db     # Volume pour stocker les données MongoDB de façon persistante
      - ./data:/data              # Volume pour accéder au dataset local depuis le conteneur
